# Generated by Django 5.2.1 on 2025-07-05 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_category_options_remove_category_icon_and_more"),
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["pack", "position"]},
        ),
        migrations.RemoveField(
            model_name="question",
            name="level",
        ),
        migrations.RemoveField(
            model_name="testattempt",
            name="level",
        ),
        migrations.CreateModel(
            name="Pack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packs",
                        to="main.level",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="pack",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quiz.pack",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testattempt",
            name="pack",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="quiz.pack"
            ),
            preserve_default=False,
        ),
    ]
