# Generated by Django 5.2.1 on 2025-07-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pack",
            name="is_used",
        ),
    ]
