# Generated by Django 5.2.1 on 2025-07-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_question_options_remove_question_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pack",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
