# Generated by Django 5.2.1 on 2025-06-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
