# Generated by Django 5.2.1 on 2025-06-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
    ]
