# Generated by Django 5.2.1 on 2025-07-12 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_refresh_token"),
        ("main", "0005_alter_category_options_remove_category_icon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERUSER", "Superuser"),
                    ("EDU_CENTER", "Education Center"),
                    ("BRANCH", "Branch Admin"),
                    ("STUDENT", "Student"),
                    ("ACCOUNTANT", "Accountant"),
                ],
                default="STUDENT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CenterPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edu_center",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="main.educationcenter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Center Payment",
                "verbose_name_plural": "Center Payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
