# Generated by Django 5.2.1 on 2025-07-12 07:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_role_centerpayment"),
        ("main", "0005_alter_category_options_remove_category_icon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyCenterReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("total_applications", models.PositiveIntegerField(default=0)),
                (
                    "payable_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edu_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_reports",
                        to="main.educationcenter",
                    ),
                ),
            ],
            options={
                "unique_together": {("edu_center", "year", "month")},
            },
        ),
    ]
