# Generated by Django 5.2.1 on 2025-07-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_paidamountlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paidamountlog",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
