# Generated by Django 5.2.1 on 2025-07-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_paidamountlog_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="centerpayment",
            name="paid_amount",
        ),
    ]
