# Generated by Django 5.2.1 on 2025-05-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationcenter",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="education_centers", to="main.category"
            ),
        ),
    ]
