# Generated by Django 5.2.1 on 2025-07-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_banner_language_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="image",
        ),
        migrations.AddField(
            model_name="banner",
            name="image_en",
            field=models.ImageField(default=1, upload_to="banners/en/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="banner",
            name="image_ru",
            field=models.ImageField(default=1, upload_to="banners/ru/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="banner",
            name="image_uz",
            field=models.ImageField(default=1, upload_to="banners/uz/"),
            preserve_default=False,
        ),
    ]
