# Generated by Django 5.2.1 on 2025-05-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_teacher_education_center_teacher_branch"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("name", "branch")},
        ),
        migrations.RemoveField(
            model_name="course",
            name="edu_center",
        ),
    ]
