# Generated by Django 5.2.1 on 2025-07-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_banner_image_banner_image_en_banner_image_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Category icon (e.g. 64×64 PNG)",
                null=True,
                upload_to="category_icons/",
            ),
        ),
    ]
