# Generated by Django 5.2.1 on 2025-07-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_category_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="category",
            name="icon",
        ),
        migrations.AddField(
            model_name="category",
            name="icon_class",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
