# Generated by Django 5.2.1 on 2025-06-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_educationcenter_cover_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="city",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="country",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="region",
        ),
        migrations.AddField(
            model_name="branch",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
    ]
