# Generated by Django 5.2.1 on 2025-06-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_branch_phone_number_branch_work_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="telegram_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
