# Generated by Django 5.2.1 on 2025-06-01 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_branch_telegram_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="time",
            new_name="start_time",
        ),
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
        migrations.AddField(
            model_name="event",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="main.branch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="requirements",
            field=models.CharField(
                choices=[("FREE", "Bepul"), ("PAID", "Pullik")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
