# Generated by Django 5.2.1 on 2025-06-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_enrollment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={"ordering": ["-applied_at"]},
        ),
    ]
