# Generated by Django 5.2.1 on 2025-06-13 10:44

import django.core.validators
import django.db.models.deletion
import django_quill.fields
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_enrollment_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Quiz Type",
                "verbose_name_plural": "Quiz Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Sequential number (e.g. 1,2,3…)", unique=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("topic", models.CharField(blank=True, max_length=70)),
                ("description", django_quill.fields.QuillField(blank=True, null=True)),
                (
                    "points",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("show_select", models.BooleanField(default=True)),
                ("audio", models.FileField(blank=True, null=True, upload_to="audio/")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="quiz_pics/"),
                ),
                (
                    "quiz_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.quiztype"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        default=main.models.get_last_unit,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="main.unit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
                "ordering": ["unit__number", "quiz_type__name", "name"],
                "unique_together": {("unit", "name")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordering within the quiz."
                    ),
                ),
                ("text", models.TextField()),
                ("end_text", models.TextField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        default=main.models.get_last_quiz,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="main.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["quiz__id", "position"],
                "unique_together": {("quiz", "text")},
            },
        ),
    ]
