# Generated by Django 5.2.1 on 2025-06-13 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_quiztype_unit_quiz_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="The answer text shown to the user."),
                ),
                (
                    "correct",
                    models.BooleanField(
                        default=False,
                        help_text="Marks whether this answer is the correct one.",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=1, help_text="Order of this answer among its siblings."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        help_text="The question this answer belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="main.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
                "ordering": ["question__id", "position"],
                "unique_together": {("question", "text")},
            },
        ),
    ]
