# Generated by Django 5.2.1 on 2025-06-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="cancelled_reason",
            field=models.TextField(
                blank=True, help_text="If status=CANCELED, give a reason", null=True
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELED", "Canceled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
