# Generated by Django 5.2.1 on 2025-06-23 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_enrollment_cancelled_reason_enrollment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="level",
            options={"ordering": ["category__name", "name"]},
        ),
        migrations.AddField(
            model_name="level",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                to="main.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="level",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="level",
            unique_together={("category", "name")},
        ),
    ]
