# Generated by Django 5.2.1 on 2025-06-26 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_level_options_level_category_alter_level_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="admins",
        ),
    ]
