# Generated by Django 5.2.1 on 2025-06-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_remove_branch_admins"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="name",
            new_name="full_name",
        ),
    ]
