name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true
      DEBUG: true
      SECRET_KEY: test-secret-key

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create & activate venv, install deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 coverage

      - name: Lint with flake8
        run: |
          source venv/bin/activate
          flake8 .

      - name: Run tests with coverage
        run: |
          source venv/bin/activate
          coverage run -m pytest
          coverage report
