name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host:     ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }} 
          # key:    ${{ secrets.SERVER_SSH_KEY }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port:     22
          script: |
            set -e
            cd /opt/EduCompass

            # Discard any local changes so git pull never fails
            git reset --hard HEAD
            git clean -fd

            git pull origin main

            source venv/bin/activate
            pip install --upgrade pip setuptools wheel
            pip install --no-cache-dir -r requirements.txt

            # Fake‐apply the broken quiz migration to sync migration history
            python manage.py migrate quiz 0002 --fake || true

            # Now apply all remaining migrations normally
            python manage.py migrate

            sudo supervisorctl restart educompass
